version: '3.7'

services:
  app:
    image: registry.digitalocean.com/a-players/askchat-server:base
    platform: linux/amd64
    working_dir: /application
    volumes:
      - .:/application

  rabbitmq-management:
    build:
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15671:15671
      - 15672:15672
      - 5671:5671
      - 5672:5672
